---
title: "Aula 01: Introdução à Jurimetria"
subtitle: "Boas vindas !"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["css/xaringan-themer.css", "default", "css/custom-css.css"]
    nature:
      ratio: "16:12"
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
# knit: pagedown::chrome_print
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  fig.align = "center",
  out.width = "90%",
  message = FALSE,
  warning = FALSE
)
xaringanExtra::use_panelset()
```


# Nos conhecendo melhor

Foto minha

Foto do Julio

---
class: middle, center

# Para conhecer vocês

### Respondam a este formulário por favor! 

https://forms.gle/HStRPDK2jVsJNDts5

---
# Plano de aula
1. Apresentar o curso
  1. Ementa
  2. Dinâmica de aula
2. Discutir o que é jurimetria
---
class: middle, center

# Sobre o curso

---
# Ementa

1. Metodologia quantitativa
  1. Definindo escopo (geográfico e temporal)
  1. Operacionlização de conceitos
  1. Perguntas de pesquisa
  1. Processo de geração de dados
2. Estatística descritiva
  1. Tipos de variáveis
      1. Variáveis categóricas
      1. Variáveis numéricas
  1. Medidas
      1. Para variáveis categóricas
      1. Para variáveis numéricas (medidas de centro e de dispersão)
  1. Visualizações
      1. Para variáveis categóricas
      1. Para variáveis numéricas

---
|Semana|Aula|Data|Conteúdo|
|:----:|:--:|:--:|:------:|
|1|1| 06/09/2022|Introdução|
|1|2| 08/09/2022|Metodologia I (Operacionalização de conceitos)|
|2|3| 13/09/2022|Metodologia II (Processo de geração de dados)|
|2|4| 15/09/2022|Metodologia III (Viés de seleção e o Teorema de Priest & Klein)|
|3|5| 20/09/2022|Trabalho parcial|
|3|6| 22/09/2022|Medidas I (Tabela de frequência)|
|4|7| 27/09/2022|Medidas II (Medidas de centro)|
|4|8| 29/09/2022|Medidas III (Medidas de dispersão)|
|5|9| 04/10/2022|Aula de exercícios sobre Medidas|
|5|10| 06/10/2022|Visualizações|
|6|11| 11/10/2022|Aula de exercícios sobre Visualizações|
|6|12| 13/10/2022|Uma técnica de pesquisa em jurimetria|
|7|13| 18/10/2022|Trabalho final|
|7|14| 25/10/2022|Trabalho final|

---
# Dinâmica de aula

As aulas terão 2 horas de duração. Há dois formatos de aulas que iremos intercalar: aulas expositivas e aulas de metodologias ativas. 

### Aulas expositivas
- Em dias de metodologias ativas, as aulas expositivas irão durar os primeiros 30 minutos da aula
- Em dias sem metodologia ativa, a aula expositiva durará as 2 horas completa da aula

### Metodologias ativas 
- Aprendizagem baseada em problemas
- Peer instruction
- Rotação de estações

---
class: middle, center

# E o que é jurimetria?

---
# Definição

> "A jurimetria é uma disciplina do conhecimento que utiliza a metodologia estatística para investigar o funcionamento de uma ordem jurídica"

NUNES, Marcelo Guedes. **Jurimetria: Como a Estatística Pode Reinventar o Direito**. São Paulo: Revista dos Tribunais. 1a ed. 2016, p. 115.

1. O que é: Disciplina do conhecimento
1. Qual é o método: Utiliza metodologia estatística
1. Qual é o objeto: Investiga o funcionamento de uma ordem jurídica

---
# Problemas epistemológicos

1. Problema geral de pesquisas empíricas no Direito: Jurimetria é uma área **do** Direito? Ou são meramente pesquisas **sobre** o Direito?

2. Problema geral de métodos quantitativos: Que tipo de perguntas podem ser feitas a respeito do Direito? A que conclusões podem tirar? E o que não podemos enxergar?

3. Problema lógico entre o *ser* e o *dever ser*: Se o Direito é uma ciência normativa, que faz afirmações a respeito do mundo do *dever ser*, o que podemos concluir a seu respeito quando *descrevemos* o mundo a partir da estatística?

4. Problema em relação a outras áreas de métodos quantitativos no Direito: Qual é a diferença entre Jurimetria e a Análise Econômica do Direito (*Law & Economics*)? 

---
class: middle, center

# Fim
