---
title: "Medidas"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["css/xaringan-themer.css", "default", "css/custom-css.css"]
    nature:
      ratio: "16:12"
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
# knit: pagedown::chrome_print
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  fig.align = "center",
  out.width = "90%",
  message = FALSE,
  warning = FALSE
)
xaringanExtra::use_panelset()
```

---
# Roteiro geral das aulas

Vamos começar vendo os tipos de variávies, que, basicamente, podem ser dois: variáveis categóricas e variáveis numéricas. 

Depois, vamos ver as medidas desses tipos de variáveis:
1. Medidas de variáveis categóricas: Tabelas de frequência
2. Medidas de variáveis numéricas:
  1. Medidas de centro:
      1. Moda
      1. Média
      1. Mediana
  1. Medidas de dispersão:
      1. Desvio médio
      1. Variância
      1. Desvio padrão
      1. Amplitude
      1. IQR
---
class: middle, center, tema1
# Tipos de variáveis

---
class: tema1
# Tipos de variáveis

### Variáveis qualitativas/categóricas

Variáveis ordinais: As categorias possuem uma ordenação universal entre si

Variáveis nominais: As categorias não possuem uma ordenação universal entre si

### Variáveis quantitativas/numéricas

Variáveis discretas: Representa números inteiros (exclui números fracionados e negativos).

Variáveis contínuas: Representa números reais

---
class: middle, center, tema2
# Medidas de Variáveis Categóricas

---
class: tema2
# Tabela de frequência

|variável $x_i$  |frequência $n_i$|frequência acumulada $N_i$|proporção $f_i$     |proporção acumulada $F_i$|porcentagem $100 f_i$|
|:--------------:|:--------------:|:------------------------:|:------------------:|:-----------------------:|:---------------------:|
|resposta 1 $x_1$| $n_1$          | $N_1=n_1$                | $f_1=\frac{n_1}{n}$| $F_1=f_1$               | $100f_1$              |
|resposta 2 $x_2$| $n_2$          | $N_2=N_1+n_2$            | $f_2=\frac{n_2}{n}$| $F_2=F_1+f_2$           | $100f_2$              |
|resposta 3 $x_3$| $n_3$          | $N_3=N_2+n_3$            | $f_3=\frac{n_3}{n}$| $F_3=F_2+f_3$           | $100f_3$              |
| $...$          | $...$          | $...$                    | $...$              | $...$                   | $...$                 |
|resposta k $x_k$| $n_k$          | $N_k=N_1+n_k$            | $f_k=\frac{n_k}{n}$| $F_k=F_{k-1}+f_k$       | $100f_k$              |

---
class: middle, center

# Medidas para variáveis numéricas

---
# Medidas de centro - Média

$\frac{1}{n} \sum_{i=i}^{n} x_{i}$

---
# Medidas de centro - Mediana

---
# Medidas de centro - Moda

---
# Medidas de dispersão

