---
title: "Medidas"
subtitle: "Tabela de frequência"
format: 
  revealjs:
    theme: [default, css/custom-css.scss]
editor: visual
---

## Ementa do curso {.smaller}

1.  Tipos de variáveis
2.  Medidas de variáveis categóricas: Tabelas de frequência
3.  Medidas de variáveis numéricas I: Medidas de centro
    1.  Média

    2.  Mediana

    3.  Moda
4.  Medidas de variáveis numéricas II: Medidas de dispersão
    1.  Desvio médio

    2.  Variância

    3.  Desvio padrão

    4.  Amplitude

    5.  IQR

## Ementa do curso {.smaller visibility="uncounted"}

1.  Tipos de variáveis
2.  **Medidas de variáveis categóricas: Tabelas de frequência**
3.  Medidas de variáveis numéricas I: Medidas de centro
    1.  Média

    2.  Mediana

    3.  Moda
4.  Medidas de variáveis numéricas II: Medidas de dispersão
    1.  Desvio médio

    2.  Variância

    3.  Desvio padrão

    4.  Amplitude

    5.  IQR

# Medidas de variáveis categóricas

##  {.smaller}

+----------+------------+----------------------+---------------------+---------------------+-------------+
| Variável | Frequência | Frequência acumulada | Proporção           | Proporção acumulada | Porcentagem |
|          |            |                      |                     |                     |             |
| $x_i$    | $n_i$      | $N_i$                | $f_i$               | $F_i$               | $100 f_i$   |
+==========+============+======================+=====================+=====================+=============+
| $x_1$    | $n_1$      | $N_1=n_1$            | $f_1=\frac{n_1}{n}$ | $F_1=f_1$           | $100f_1$    |
+----------+------------+----------------------+---------------------+---------------------+-------------+
| $x_2$    | $n_2$      | $N_2=N_1+n_2$        | $f_2=\frac{n_2}{n}$ | $F_2=F_1+f_2$       | $100f_2$    |
+----------+------------+----------------------+---------------------+---------------------+-------------+
| $x_3$    | $n_3$      | $N_3=N_2+n_3$        | $f_3=\frac{n_3}{n}$ | $F_3=F_2+f_3$       | $100f_3$    |
+----------+------------+----------------------+---------------------+---------------------+-------------+
| ...      | ...        | ...                  | ...                 | ...                 | ...         |
+----------+------------+----------------------+---------------------+---------------------+-------------+
| $x_k$    | $n_k$      | $N_k=N_{k-1}+n_k$    | $f_k=\frac{n_k}{n}$ | $F_k=F_{k-1}+f_k$   | $100f_k$    |
+----------+------------+----------------------+---------------------+---------------------+-------------+

: Tabela de frequência

# Fim
