---
title: "Trabalho final (parte I)"
subtitle: "Produção da metodologia do trabalho"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["css/xaringan-themer.css", "default", "css/custom-css.css"]
    nature:
      ratio: "16:12"
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
# knit: pagedown::chrome_print
---
### Instruções para o trabalho final

O trabalho final será a entrega de uma análise jurimétrica. A entrega final será dividida em 2 partes. A primeira parte será simplesmente criar a metodologia do trabalho e será realizada hoje. A última parte será a realização das análises em si. 

Vocês devem se atentar para:
1. Qual é a sua pergunta de pesquisa? Pensar na pergunta teórica
1. Qual é o escopo geográfico e temporal da sua pesquisa?
1. Como a sua pergunta teórica será operacionalizada?
1. Que dados vão ser utilizados para responder à pergunta?
1. Você vai usar uma base de dados pronta ou vai gerar seus próprios dados?
1. Qual é a sua população?
1. Será um trabalho amostral ou populacional?
1. Como esses dados foram gerados?

Recomendamos que vocês reproduzam a metodologia de pesquisa em que vocês _criam_ os dados a partir de formulários de classificação. 

