---
title: "Exercícios: Medidas"
author: "ABJ"
output: pdf_document
---

# Orientações gerais

- Serão formados 6 grupos de 5 pessoas;
- Os grupos terão 2 horas para responder às questões;
- Um único aluno será encarregado de anotar as respostas de todas as questões discutidas no grupo;
- Depois das discussões em grupo, retornaremos à sala para discutir as questões conjuntamente;
- Teremos um breve intervalo antes de voltarmos à sala;
- As bases para o exercício podem ser encontradas no seguinte link: <https://docs.google.com/spreadsheets/d/18icIOI2XZX4NR54upLsN0CnLRkyeo6ryQYsTKrZQxL0/edit?usp=sharing>. 
- Baixe a base localmente e incorpore-a no seu Drive para fazer os exercícios. - Não leia os textos completos, não há tempo para isso. Há a indicação das páginas necessárias nos próprios enunciados dos exercícios;
- Será tarefa avaliativa uma entrega INDIVIDUAL dos exercícios
- Elaboramos um cheat sheet para você, caso seja necessária alguma cola a respeito de alguma função do gsheets. 


## I) Exercício 1: Medidas para variáveis categóricas

**1) Faça a tabela de frequência das variáveis assunto e dec_val, incluindo a frequência ($n_i$), proporção ($f_i$) e porcentagem ($100*f_i$)**

**2) Refaça a tabela do item anterior, como Tabela Dinâmica**

**3) Refaça a tabela do item anterior, apenas com a contagem de casos por assunto e a taxa de reforma (em que considera-se como reformou apenas os resultados "Reformou" ou "Parcial"). Espera-se que a tabela final tenha 4 colunas: assunto, frequência, contagem de casos reformados e taxa de reforma.**

**4) Interprete os resultados da tabela do item 3**

## II) Exercício 2: Medidas para variáveis numéricas (medidas centrais)

**1) Calcule o IDH médio do Brasil**

**2) Calcule o IDH médio de cada região do Brasil**

**3) Quais regiões estão abaixo da média brasileira? Retorne a resposta em uma tabela, de três colunas: Região, Média do IDH (para a região), Abaixo da média do BR (VERDADEIRO/FALSO)**

**4) Calcule o IDH médio de cada Estado do Brasil**

**5) Calcule a mediana do IDH brasileiro**

**6) Compare a média brasileira com a mediana brasileira. Elas são muito diferente entre si? O que isso indica sobre a distribuição dos dados?**

**7) De acordo com a sua resposta no item 6, responda se, neste caso, é preferível utilizar a média ou a mediana para representar a medida central dos dados?**

## III) Exercício 3: Medidas para variáveis numéricas (medidas de dispersão - desvio)

**1) Calcule o IDH médio do Brasil**

**2) Calcule os desvios de cada município em relação à média. Para isso, crie uma coluna nova**

**3) Calcule a média dos desvio**

**4) Explique o resultado do item 3**

**5) Como podemos arrumar o problema apresentado no item 4? Apresente todas as soluções possíveis, explicando como elas resolvem o problema gerado na conta da média dos desvios**

**6) Aplique as soluções discutidas no caso atual, atualizando as células da planilha com os valores "corrigidos" do desvio**

**7) Calcule o desvio médio e o desvio padrão. Os resultados foram iguais? Por quê?**

## IV) Exercício 4: Medidas para variáveis numéricas (medidas de dispersão - amplitude e IQR)

**1) Calcule os quantis empíricos de 12%, 65% e 99%**

**2) Faça uma tabela com os principais quantis empíricos (mínimo, quantil inferior, mediana, quantil superior, máximo)**

**3) Calcule a amplitude e o IQR**

**4) Calcule o IQR dos Estados de GO e DF e interprete os resultados**

**5) Calcule a amplitude dos Estados de GO e DF e interprete os resultados, comparando com o IQR**
