---
title: "Exercícios: Operacionalização de conceitos"
author: "ABJ"
output: pdf_document
---

# Orientações gerais

- Formem grupos de 5 alunos. Todas as questões deverão ser respondidas nestes grupos;
- Os grupos terão de 40 minutos a 1 hora para responder às questões;
- Um único aluno será encarregado de anotar as questões discutidas no grupo;
- Depois das discussões em grupo, retornaremos à sala para discutir as questões conjuntamente;
- Outro aluno, que não aquele encarregado de anotar, deverá ler as respostas;
- Para responder aos exercícios, os alunos deverão acessar dois textos que estão no Drive, no link: https://drive.google.com/file/d/17G9XRHePcq6rlq9w061Yj5HQ3JxJKsoh/view?usp=sharing
- Não leia os textos completos, não há tempo para isso. Há a indicação das páginas necessárias nos próprios enunciados dos exercícios;

## I) Exercícios referentes ao texto "Sundfeld et al, 2011". 

**Ler páginas 12 a 17 do texto, começando em "II. Escolhas metodológicas e justificativas" e acabando em "II.2 Desenho de pesquisa". Não precisa ler a partir de "II.2.1 Análise quantitativa: o que chega e o que faz o STF".**

#### Exercício 1. Qual é o conceito que está sendo estudado? 

Judicialização da política

#### Exercício 2. Como esse conceito está sendo visualizado na prática? 

Por meio de ações constitucionais que versem sobre a separação dos poderes.

"A despeito das dificuldades anteriormente apontadas a respeito da caracterização do que seriam questões essencialmente políticas como um âmbito temático ou locus propício para a ocorrência do fenômeno da judicialização, a presente pesquisa procurou evitar tais problemas por meio da seguinte escolha: tratar exclusivamente de ações envolvendo controle de constitucionalidade." (p. 14)

#### Exercício 3. Como os autores justificam essa operacionalização? 

"Por mais que seja problemático o conteúdo semântico da judicialização da política,
parece razoável assumir que problemas de ordem constitucional (ainda que não em todos os casos) possam, em geral, ser caracterizados como questões de natureza política. Dessa forma, acredita-se que, com esse recorte ex ante, por mais que muitos casos relevantes para a judicialização fiquem de fora, abarca-se uma parte expressiva das questões e problemas levados ao STF que tenham a configuração de disputas políticas. Em outras palavras, parte-se da premissa de que o controle de constitucionalidade seria um âmbito privilegiado para observação da interação entre Poderes e também do suposto fenômeno da judicialização da política." (p. 14)

#### Exercício 4. Discorra criticamente sobre essa operacionalização.

#### a) O que fica de fora com essa operacionalização?

A política pode ser discutida em outras ações. Um exemplo são as ações civis públicas e ações populares. 

#### b) Que impactos que isso pode ter para os resultados?

Retirar da análise ações civis públicas e ações populares significa retirar da análise ações cuja competência são da sociedade civil. Pelo art. 103 da Constituição Federal, são legitimados a propor ADIN e ADC:

1. o Presidente da República;
1. a Mesa do Senado Federal;
1. a Mesa da Câmara dos Deputados;
1. a Mesa de Assembléia Legislativa ou da Câmara Legislativa do Distrito Federal;
1. o Governador de Estado ou do Distrito Federal;
1. o Procurador-Geral da República;
1. o Conselho Federal da Ordem dos Advogados do Brasil;
1. partido político com representação no Congresso Nacional;
1. confederação sindical ou entidade de classe de âmbito nacional.

Ou seja, são legitimados a entrar com ações constitucionais apenas atores institucionais partidários. 

Para ações civis públicas e para ações populares, há outros legitimados. 

No art. 5, LXXIII da CF há a previsão de que "qualquer cidadão é parte legítima para propor ação popular". Já para as ações civis públicas, o art. 5, V da Lei de Ação Civil Pública (Lei 7.347/1985) prevê que "têm legitimidade para propor a ação principal e a ação cautelar: V - a associação que, concomitantemente: a) esteja constituída há pelo menos 1 (um) ano nos termos da lei civil; b) inclua, entre suas finalidades institucionais, a proteção ao patrimônio público e social, ao meio ambiente, ao consumidor, à ordem econômica, à livre concorrência, aos direitos de grupos raciais, étnicos ou religiosos ou ao patrimônio artístico, estético, histórico, turístico e paisagístico."

Assim, ao se ignorar as ações civis públicas e as ações populares, a sociedade civil organizada não participa dessa "política" que está sendo analisada no estudo. Então esse estudo está avaliando a judicialização da política por atores institucionais apenas. É uma ressalva importantíssima essa. 

#### c) A premissa para realizar essa operacionalização é forte ou fraca?

Se o estudo pretende falar da política em geral, é uma premissa forte 

## II) Exercícios referentes ao texto "Yeung e Azevedo, 2017"

#### Exercício 1. Qual é o conceito que está sendo visualizado? 

Viés judicial pró-devedor

#### Exercício 2. Como esse conceito está sendo visualizado na prática? 

Proporção de ações fávoráveis ao devedor no STJ

#### Exercício 3. No artigo de Yeung e Azevedo, 2017, os autores escrevem:

> Dado que este trabalho foca na questão do viés judicial, a pergunta imediata seria: o que é viés judicial? A definição literal para 'viés' é 'oblíquo' ou 'em diagonal', ou seja, algo que não segue o padrão ou o sentido usual. Portanto, uma decisão judicial com viés seria uma que não é 'reta' ou 'direita', que é 'oblíqua' em alguma direção. O grande problema é definir qual seria a decisão 'reta/direita' para cada um dos casos que chega ao Judiciário. Mais difícil ainda seria afirmar que o Judiciário brasileira como um todo, ou o grupo de magistrados, tem viés. Isso implicaria dizer que suas decisões são, no todo ou na maioria, 'oblíquas'. **Como testar isso sem observar o comportamento sem viés?** Simplesmente não é possível. (p. 329, grifos nossos)

#### Com base no trecho acima, responda: qual é a importância de se testar o viés observando o camportamento sem viés?

A importância de se estudar os casos sem viés é ter um grupo de comparação em relação ao viés. Sem esse parâmetro, ficamos sem norte para definirmos se houve viés ou não.

Depois, veremos o Teorema de Priest & Klein. Com isso, vamos poder refinar essa resposta. Com o teorema vamos ver que não precisamos observar o comportamento sem viés, pois podemos supor que o comportamento sem viés seja um comportamento em que 50% das decisões são a favor do devedor, e 50% a favor do credor. 

Por hora, como ainda não vimos o teorema, podemos afirmar que a comparação com o grupo "sem viés" serve para se ter um parâmetro do que significa o viés. 

#### Exercício 4. Yeung e Azevedo, 2017, na parte 5 do artigo, entitulada "Definindo o que é viés e o que não é viés", reconhecem dois viéses possíveis que estão para-além da decisão do juiz. 

#### a) Quais são os viéses que os autores reconhecem? Descreva os seus funcionamentos.

Viés do fato: "Pode, contudo, acontecer de os recursos chegarem ao STJ de maneira *não-aleatória*. Por exemplo, eles poderiam ser 'naturalmente' mais favoráveis ao devedor. Neste caso, mesmo que os magistrados consistentemente decidissem a favor do devedor, isso não poderia ser considerado um viés da decisão, mas sim um *viés do fato*. Em outras palavras, se a maior parte dos processos que chegassem ao STJ contivessem fatos que favorecessem o devedor, mesmo magistrados neutros tenderiam a decidir dando ganho de causa a esta parte. Infelizmente, este é um problema a que estão sujeitos todos os estudos de decisões judiciais que somente observam os casos levados ao judiciário. Espera-se que trabalhos futuros consigam lidar com este assunto de forma mais adequada." (p. 330)

Viés legislativo: "Além do viés do fato, existe outra falsa fonte de viés judicial, que Falcão, Schuartz e Arguelhes (2006) chamam de *viés legislativo*. Segundo estes autores, o suposto viés anti-credor não é criado pelo juiz no momento da tomada da decisão judicial, mas em um momento anterior, talvez na criação das leis ou das normas legais pelo Executivo e/ou Legislativo. O magistrado, como membro do Poder Judiciário, tem a função e o dever de respeitar tais leis. Neste caso, mesmo que a decisão judicial acabe por favorecer – “devida” ou “indevidamente” – uma ou outra parte, não significa que o juiz julgou com viés: ele apenas cumpriu sem papel e não teria responsabilidade por ter favorecido uma ou outra parte. O viés não é de sua decisão." (p. 330)

#### b) O estudo encontrou as seguintes proporções de vitória de litígios:

|      Tipo Recorrente     |      Tipo Recorrido      | Decisão: Não conhecido/Não provido | Decisão: Provido (Parcial ou Total) |
|:------------------------:|:------------------------:|:----------------------------------:|:-----------------------------------:|
| Pessoa Física            | Pessoa Física            | 59,12%                             | 40,88%                              |
| Pessoa Física            | Pessoa Jurídica          | 55,35%                             | 44,65%                              |
| Pessoa Física            | Inst. Financeiras | 51,52%                             | 48,48%                              |
| Pessoa Jurídica          | Pessoa Física            | 49,71%                             | 50,29%                              |
| Pessoa Jurídica          | Pessoa Jurídica          | 45,87%                             | 54,41%                              |
| Pessoa Jurídica          | Inst. Financeiras | 42,08%                             | 57,92%                              |
| Inst. Financeiras | Pessoa Física            | 40,33%                             | 59,67%                              |
| Inst. Financeiras | Pessoa Jurídica          | 36,68%                             | 63,31%                              |
| Inst. Financeiras | Inst. Financeiras | 33,19%                             | 66,81%                              |


#### Antes de olhar para a tabela, pense abstratamente nos conflitos entre Pessoas Jurídicas (Recorrente) e Instituições Financeiras (Recorrida) e nos conflitos entre Instituições Financeiras (Recorrente) e Pessoas Jurídicas (Recorrida) e responde: o que seria um resultado pró-credor e um resultado pró-devedor em cada um desses conflitos? 

Para os conflitos entre Pessoas Jurídicas (Recorrente) e Instituições Financeiras (Recorrida), o resultado pró-devedor seria o resultado de decisões de provimento parcial ou total e o resultado pró-credor seria o resultado de decisões não conhecidas ou não providas. 

Para os conflitos entre Instituições Financeiras (Recorrente) e Pessoas Jurídicas (Recorrida), os resultados se invertem: o resultado pró-devedor seria o resultado de decisões não conhecidas ou não providas e o resultado pró-credor seria o resultado de provimento parcial ou total das decisões. 

#### c) E, agora, olhando para a tabela, o resultado foi pró-quem nestes dois tipos de conflito?

Para os conflitos entre Pessoas Jurídicas (Recorrente) e Instituições Financeiras (Recorrida), o resultado foi pró-devedor. 

Para os conflitos entre Instituições Financeiras (Recorrente) e Pessoas Jurídicas (Recorrida), o resultado foi pró-credor. 

#### d) Comente, a partir dos viéses descritos no item (a) desta questão, se os resultados pró-devedor ou pró-credor do item (c) podem indicar um viés pró-devedor ou pró-credor dos magistrados?

O resultado pró-devedor dos conflitos entre Pessoas Jurídicas (Recorrente) e Instituições Financeiras (Recorrida) pode ser ampliado para dizer que há um viés pró-devedor, mas com ressalvas, pois as decisões pró-devedor podem ter sido decisões com viés de fato ou com viés legislativo. Supõe-se que os devedores não tenham

Já o resultado pró-credor dos conflitos entre Instituições Financeiras (Recorrente) e Pessoas Jurídicas (Recorrida) não pode ser ampliado para dizer que o Judiciário possui um viés pró-credor. O que acontece é que, nas ações em que as instituições financeiras são as recorrentes, a escolha de ajuizar as ações está nas mãos do próprio credor. Dessa forma, eles podem, a partir de uma litigância estratégica, ingressar com recursos somente nos casos em que eles têm maior probabilidade de êxito. 

#### c) O que a conclusão do item (b) nos diz sobre a operacionalização do conceito?

A operacionalização do conceito foi a operacionalização de utilizar a proporção de decisões pró-devedor (plano empírico) para dizer que há um viés judicial pró-devedor (plano abstrato). Essa operacionalização apresenta algumas fragilidades, pois as conclusões que tiramos sobre o viés judicial (conceito abstrato) a partir das decisões (variável) estão contaminadas com os viéses de fato e legislativo. 
