---
title: "Exercícios: Operacionalização de conceitos"
author: "ABJ"
output: pdf_document
---

# Orientações gerais

- Formem grupos de 5 pessoas. Todas as questões deverão ser respondidas nestes grupos;
- Os grupos terão de 40 minutos a 1 hora para responder às questões;
- Um único aluno será encarregado de anotar as respostas às questões discutidas no grupo;
- Depois das discussões em grupo, retornaremos à sala para discutir as questões conjuntamente;
- Outro aluno, que não aquele encarregado de anotar, deverá ler as respostas quando discutidas em grupo;
- Para responder aos exercícios, os alunos deverão acessar dois textos que estão no Drive, no link: https://drive.google.com/drive/folders/1mrogYNLA5x9cCzw4sTQWBOUtTGOPKyB1?usp=sharing
- Não leia os textos completos, não há tempo para isso. Há a indicação das páginas necessárias nos próprios enunciados dos exercícios;

## I) Exercícios referentes ao texto "Sundfeld et al, 2011". 

**Ler páginas 12 a 17 do texto, começando em "II. Escolhas metodológicas e justificativas" e acabando em "II.2 Desenho de pesquisa". Não precisa ler o que vem a partir de "II.2.1 Análise quantitativa: o que chega e o que faz o STF".**

#### Exercício 1. Qual é o conceito que está sendo estudado? 

Judicialização da política

#### Exercício 2. Como esse conceito está sendo visualizado na prática? 

Por meio de ações constitucionais que versem sobre a separação dos poderes.

"A despeito das dificuldades anteriormente apontadas a respeito da caracterização do que seriam questões essencialmente políticas como um âmbito temático ou locus propício para a ocorrência do fenômeno da judicialização, a presente pesquisa procurou evitar tais problemas por meio da seguinte escolha: tratar exclusivamente de ações envolvendo controle de constitucionalidade." (p. 14)

#### Exercício 3. Como os autores justificam essa operacionalização? 

"Por mais que seja problemático o conteúdo semântico da judicialização da política, parece razoável assumir que problemas de ordem constitucional (ainda que não em todos os casos) possam, em geral, ser caracterizados como questões de natureza política. Dessa forma, acredita-se que, com esse recorte ex ante, por mais que muitos casos relevantes para a judicialização fiquem de fora, abarca-se uma parte expressiva das questões e problemas levados ao STF que tenham a configuração de disputas políticas. Em outras palavras, parte-se da premissa de que o controle de constitucionalidade seria um âmbito privilegiado para observação da interação entre Poderes e também do suposto fenômeno da judicialização da política." (p. 14)

#### Exercício 4. Discorra criticamente sobre essa operacionalização.

#### a) O que fica de fora com essa operacionalização?

A política pode ser discutida em outras ações. Um exemplo são as ações civis públicas e ações populares. 

#### b) Que impactos que isso pode ter para os resultados?

Retirar da análise ações civis públicas e ações populares significa retirar da análise ações cuja competência são da sociedade civil. Pelo art. 103 da Constituição Federal, são legitimados a propor ADIN e ADC:

1. o Presidente da República;
1. a Mesa do Senado Federal;
1. a Mesa da Câmara dos Deputados;
1. a Mesa de Assembléia Legislativa ou da Câmara Legislativa do Distrito Federal;
1. o Governador de Estado ou do Distrito Federal;
1. o Procurador-Geral da República;
1. o Conselho Federal da Ordem dos Advogados do Brasil;
1. partido político com representação no Congresso Nacional;
1. confederação sindical ou entidade de classe de âmbito nacional.

Ou seja, são legitimados a entrar com ações constitucionais apenas atores institucionais partidários. 

Para ações civis públicas e para ações populares, há outros legitimados. 

No art. 5, LXXIII da CF há a previsão de que "qualquer cidadão é parte legítima para propor ação popular". Já para as ações civis públicas, o art. 5, V da Lei de Ação Civil Pública (Lei 7.347/1985) prevê que "têm legitimidade para propor a ação principal e a ação cautelar: V - a associação que, concomitantemente: a) esteja constituída há pelo menos 1 (um) ano nos termos da lei civil; b) inclua, entre suas finalidades institucionais, a proteção ao patrimônio público e social, ao meio ambiente, ao consumidor, à ordem econômica, à livre concorrência, aos direitos de grupos raciais, étnicos ou religiosos ou ao patrimônio artístico, estético, histórico, turístico e paisagístico."

Assim, ao se ignorar as ações civis públicas e as ações populares, a sociedade civil organizada não participa dessa "política" que está sendo analisada no estudo. Então esse estudo está avaliando a judicialização da política por atores institucionais apenas. É uma ressalva importantíssima essa. 

#### c) A premissa para realizar essa operacionalização é forte ou fraca?

Se o estudo pretende falar da política em geral, é uma premissa forte. 

## II) Exercícios referentes ao texto "Yeung e Azevedo, 2017"

#### Exercício 1. A partir da leitura das 3 primeiras páginas da "Introdução" do artigo responda: 

#### a) Qual é o conceito teórico de interesse para o artigo? 

Viés judicial pró-devedor

#### b) Como esse conceito está sendo visualizado na prática? 

Proporção de ações fávoráveis ao devedor no STJ

#### c) Com base nas respostas anteriores, responda qual é a operacionalização que está sendo feita? 

O conceito de "viés judicial pró-devedor" está sendo operacionalizado por meio do dado empírico de "proporção de ações favoráveis ao devedor no STJ". 

#### Exercício 2. Yeung e Azevedo, 2017, na parte 5 do artigo, entitulada "Definindo o que é viés e o que não é viés", reconhecem dois viéses possíveis que estão além da decisão do juiz. 

#### a) Quais são os vieses que os autores reconhecem? Descreva-os. 

Viés do fato: "Pode, contudo, acontecer de os recursos chegarem ao STJ de maneira *não-aleatória*. Por exemplo, eles poderiam ser 'naturalmente' mais favoráveis ao devedor. Neste caso, mesmo que os magistrados consistentemente decidissem a favor do devedor, isso não poderia ser considerado um viés da decisão, mas sim um *viés do fato*. Em outras palavras, se a maior parte dos processos que chegassem ao STJ contivessem fatos que favorecessem o devedor, mesmo magistrados neutros tenderiam a decidir dando ganho de causa a esta parte. Infelizmente, este é um problema a que estão sujeitos todos os estudos de decisões judiciais que somente observam os casos levados ao judiciário. Espera-se que trabalhos futuros consigam lidar com este assunto de forma mais adequada." (p. 330)

Viés legislativo: "Além do viés do fato, existe outra falsa fonte de viés judicial, que Falcão, Schuartz e Arguelhes (2006) chamam de *viés legislativo*. Segundo estes autores, o suposto viés anti-credor não é criado pelo juiz no momento da tomada da decisão judicial, mas em um momento anterior, talvez na criação das leis ou das normas legais pelo Executivo e/ou Legislativo. O magistrado, como membro do Poder Judiciário, tem a função e o dever de respeitar tais leis. Neste caso, mesmo que a decisão judicial acabe por favorecer – “devida” ou “indevidamente” – uma ou outra parte, não significa que o juiz julgou com viés: ele apenas cumpriu sem papel e não teria responsabilidade por ter favorecido uma ou outra parte. O viés não é de sua decisão." (p. 330)

#### b) A partir destes vieses apresentados pelos autores, discorra criticamente sobre a operacionalização realizada no artigo. 

A operacionalização de "viés judicial" por meio da proporção de decisões favoráveis ao devedor no STJ possui seus limites, como vimos pelos viéses. Entretanto, os autores explicitaram com muita clareza que limites são estes. A pesquisa, dessa forma, foi objetiva e honesta ao explicitar todas as suas limitações. 

## III) Exercícios referentes ao texto "Galanter, 2018 (1941)"

### Em 1941, Marc Galanter escreveu um célebre artigo em que ele formulou uma tipologia de partes nos litígios. O artigo, no original, se chama "Why the 'Haves' Come Out Ahead", o que pode ser traduzido como "Por que 'Quem tem' Sai na Frente". Para realizar este exercício, leia as páginas 46 a 51 do pdf, em que Galanter descreve as 7 características de um "jogador habitual" (JH) e de "participante eventual" (PE). 

### Exercício 1. Descreve as características de um JH e de um PE

Um JH é aquele tipo de parte que está indo para a arena judicial pela primeira vez (é o “primeiro tiro” dele no mundo jurídico). Assim sendo, ele não possui familiaridade com as regras jurídicas, com as leis, as normas, os princípios e regulamentos. Mesmo sem esse conhecimento, ele acaba, por algum infortúnio, tendo que resolver seus problemas judicialmente. Tanto o requerente quanto o requerido podem assumir a tipologia do JH.

Já o PE é o exato oposto do JH, ele é aquele tipo de parte que está reiteradamente envolvido em algum conflito judicial. Isso lhe garante maior expertise nos embates jurídicos. Outras características importantes dos PEs são que, por estarem constantemente na frente dos juízes, eles acabam desenvolvendo relacionamentos informais com as autoridades do mundo do direito. Esses relacionamentos podem lhe conferir fama e status dentro dos tribunais, bem como lhe possibilitam tornar-se amigos íntimos ou, na pior das hipóteses, rivais dos juízes. Isso também é um fator que acaba influenciando a capacidade desses agentes em ganhar uma disputa. Outro elemento importante na caracterização dos PEs é que, além de relacionamentos com o Poder Judiciário e expertise técnica, eles dispõem de recursos que são inimagináveis, muitas vezes, para os JHs. É claro que pessoas ricas podem ser one-shooters, mas mesmo as pessoas ricas não se comparam com a quantidade de recursos que grandes agentes jurídicos possuem.

Mas de todas as diferenças entre JH e PE, existe um fator decisivo para distinguí-los, que é a questão do interesse. Sempre que os one-shooters se apresentam no Judiciário, eles possuem um único interesse: ganhar o máximo possível de um processo que eles começaram, ou perder o mínimo possível de um processo no qual eles estão sendo acusados. No fim, o que essa estratégia está buscando é resguardar os interesses materiais da parte, seja o de maximizar os ganhos (no caso de o OS ser parte autora), seja minimizar suas perdas (no case de o JH ser parte réu). Isso é o que caracteriza o interesse dos JHs nas disputas judiciais.

Os PEs, por outro lado, possuem um outro interesse. É claro que eles buscam também proteger seus interesses materiais, mas, justamente por estarem envolvidos na mesma disputa judicial repetidas vezes, eles acabam desenvolvendo um segundo tipo de interesse: o interesse normativo. A ideia é que, como esses agentes sabem que eles vão voltar para o Judiciário outras vezes, então, a fim de otimizar os seus ganhos e perdas materiais no longo prazo, eles buscam criar decisões jurídicas favoráveis a eles, isto é, criar uma jurisprudência favroável a eles. No curto prazo, isso pode dar a impressão de que os PEs estão realizando uma estratégia irracional. Mas, no longo prazo, isso não se mostra verdadeiro. A fim de evitar decisões contrárias aos PEs, esses agentes evadem do Judiciário às vezes, comprometendo-se até com acordos extrajudiciais que são mais custosos do que os danos, sanções ou reparações que eles seriam condenados a pagar se realizassem aquela disputa na frente do juiz. Esses esforços evitam que se consolidem entendimentos jurisprudenciais contrários aos interesses dos PEs.

Então, de um lado, temos JHs caracterizados por um desconhecimento e falta de familiaridade com o Judiciário, que entra nele somente para maximizar seus ganhos ou minimizar suas perdas; e, do outro, temos PEs, caracterizados por um relacionamento íntimo e prolongado com os agentes do sistema jurídico, que buscam, além de satisfazer seus interesses materiais, proteger também seus interesses normativos.

### Exercício 2. Uma pesquisadora gostaria de realizar uma pesquisa para testar se os JHs possuem, de fato, mais vantagens que os PEs nos processos. Para isso, foi necessário operacionalizar os conceitos de Jogador Habitual e Participante Eventual. A seguir, discuta algumas possibilidades de operacionalização que a pesquisadora deseja realizar. 

### a) O CNJ, em 2012, realizou um estudo a respeito dos grandes litigantes, elencando quem são os 100 maiores litigantes dos Tribunais de Justiça. Depois, em 2015, a Associação Brasileira de Magistrados atualizou os dados (mas apenas para alguns estados). A partir destes estudos, a pesquisadora decidiu operacionalizar os JHs como as partes que aparecem nestes dois estudos [não é preciso ler os relatórios para responder a essa questão].

Há várias considerações a se fazer a respeito dessa operacionalização:

1. O nome dos litigantes que consta nas listas pode variar a sua escrita ao longo dos processos. Então é possível que um litigante considerado como LH para essa pesquisa fique de fora na hora da operacionalização, simplesmente porque a grafia de seu nome está diferente do que consta nos relatórios. 
2. Por mais que essas listas dos 100 maiores litigantes apresentem partes muito frequentes no Judiciário, não é em todo processo que elas aparecerem que elas serão consideradas como JHs Em alguns processos, uma parte frequente no Judiciário pode ser uma parte inédia, meramente incidental, não possuindo qualquer expertise ou interesse normativo nela. 
3. Existem mais partes que os litigantes apresentados na lista que poderiam ser considerados como JH. 

### b) A pesquisadora coletou todos os dados para realizar a sua pesquisa, de forma que uma das informações que ela tinha era o nome de cada uma das partes. A partir disso, ela contou o número de vezes que cada um dos nomes apareciam ao longo dos processos. Como ela estava analisando apenas a Justiça Estadual, ela achou que seria razoável dizer que as partes que apareciam mais de 100 vezes seriam consideradas JHs. 

O problema dessa operacionalização é o _corte_. Qual é o corte preciso para se dizer isso? Por que não consideramos que um LH é aquele que aparece em mais de 30 processos? Ou 1000? Ao mesmo tempo em que é razoável supor que, quanto mais processos uma parte aparece, mais expertise ela tem nesse tipo de judicialização e mais ela pode desenvolver uma estratégia normativa, também não podemos dizer com muita convicção qual é o número exato de processos que uma parte precisa participar para ser considerada como um JH.

### c) A pesquisadora, a partir do nome das partes, percebeu que era possível classificá-las como pessoas jurídicas de direito público, pessoas jurídicas de direito privado e pessoas físicas, sendo que as pessoas físicas seriam sempre as partes residuais (ou seja, as que não se enquadram em nenhum critério). A partir disso, ela estabeleceu que todas as pessoas jurídicas, seja de direito público, seja de direito privado, seriam consideradas como JHs; e que todo o resto, seria considerado como PE. 

Há várias considerações a se fazer a respeito dessa operacionalização:

1. Existem pequenas empresas, tais como MEs e EPPs que definitivamente não poderiam ser consideradas como JHs. 
2. Nem toda empresa possui interesse normativo nas judicializações. 
3. As empresas podem aparecer nos processos de forma meramente incidental, não podendo ser consideradas como JH em muitas judicializações. 
4. Existe uma discussão importante se o Estado pode ser considerado um JH. A questão é que o Estado está submetido a uma série de regras que obstruem a adoção de uma atuação estratégica. O simples fato de existir o reexame necessário para questões envolvendo o fisco já faz com que o INSS não tenha o direito de escolher com que recursos entrar ou não. O mesmo ocorre com o Ministério Público, que, por causa do princípio da obrigatoriedade, não pode decidir em que casos atuar ou não. Uma vez identificado que determinado caso se situa entre suas atribuições constitucionais, não há margem de escolha para atuar ou não, o que também dificulta a adoção de uma atuação estratégica no Judiciário. Se o Estado não for considerado como um JH, a operacionalização estará totalmente equivocada. Quem discute melhor essas questões é Ananda Palazzin de Almeida. Para a discussão do INSS como um JH, ver: ALMEIDA, Ananda Palazzin de. A Atuação do INSS como Litigante Habitual no Recurso Extraordinário No 631.2401. **Revista Eletrônica de Direito Processual – REDP**, v. 21, n. 3, ano 14, set./dez., 2020. Para a discussão do MP como JH, ver: ALMEIDA, Ananda Palazzin de. **O Ministério Público como litigante habitual: uma atuação estratégica?** Dissertação (Mestrado em Direito) - Faculdade de Direito, Universidade de São Paulo, São Paulo, 2019.


### IV) Exercício sobre o gráfico

```{r, fig.width=7, fig.height=4, dpi=300}
set.seed(1)
N <- 400
tabela <- tibble::tibble(
  data_entrada = runif(N, 2010, 2021.5),
  data_saida = data_entrada + rexp(N, 1/5),
  tempo = data_saida - data_entrada
) |> 
  dplyr::mutate(observado = dplyr::if_else(
    data_saida <= 2021.5, "Observado", "Não observado"
  ))

tabela |> 
  ggplot2::ggplot() +
  ggplot2::aes(data_entrada, tempo, colour = observado,
               alpha = observado) +
  ggplot2::geom_point() +
  ggplot2::geom_abline(
    slope = -1,
    intercept = 2021.5,
    colour = 2, 
    linetype = 2
  ) +
  ggplot2::scale_x_continuous(breaks = 2010:2021) +
  ggplot2::theme_minimal(12) +
  ggplot2::labs(
    x = "Ano entrada", y = "Tempo (anos)", 
    colour = "", alpha = ""
  ) +
  ggplot2::scale_colour_viridis_d(
    option = "A", begin = .2, end = .8, direction = -1
  ) +
  ggplot2::ylim(c(0,10)) +
  ggplot2::scale_alpha_discrete(range = c(.4, 1)) +
  ggplot2::theme(legend.position = "bottom")
```
