---
title: "Exercício sobre Técnica de Pesquisa"
author: "ABJ"
format: 
  pdf:
    mainfont: Arial
    sansfont: Arial
pdf-engine: lualatex
editor: visual
lang: pt
---

## Orientações gerais

-   Formem grupos de 5 alunos. Todas as questões deverão ser respondidas nestes grupos;
-   Os grupos terão 2 horas para responder às questões;
-   Depois das discussões em grupo, retornaremos à sala para discutir as questões conjuntamente;
-   Lembrem de anotar as respostas às questões em um documento compartilhado entre vocês.

{{< pagebreak >}}

## Perguntas

**Neste exercício, queremos treinar uma habilidade essencial da realização de pesquisas em jurimetria: a listagem de processos. As questões a seguir servem para guiar as alunas e os alunos no processo de listagem.**

**1) Como um grupo, escolham um das perguntas abaixo para realizar uma pesquisa.**

**a) Uma imobiliária quer construir um prédio novo. Ela comprou o terreno, elaborou o projeto de construção e enviou a documentação para a Prefeitura. O órgão público, por sua vez, aceitou a documentação e concedeu o alvará de construção à imobiliária. Entretanto, os moradores do bairro não querem que esse prédio seja construído e, para tanto, eles entram com uma ação no TJSP. Assim, vocẽ vai pesquisar as judicializações que acontecem entre associações de moradores de bairro contra a concessão, pela Prefeitura, do alvará de construção às imobiliárias. Vocẽ quer descobrir (i) o que leva os moradores a quererem barrar a construção de novos edifícios; (ii) o que o Judiciário responde, isto é, se os pedidos são procedentes ou improcedentes;c.**

**b) Uma mãe precisa colocar o seu filho na creche para trabalhar, mas não há vagas disponíveis. Para isso, ela entra com uma ação no TJSP, buscando adquirir uma vaga na creche. Você vai pesquisar, então, a judicialização a respeito da fila de espera nas creches de São Paulo. Você quer descobrir (i) se as crianças que estão pedindo para "furar fila" tem algum motivo especial para tanto; (ii) o que o Judiciário responde a estes casos; e (iii) o tempo de resposta**

### Informações sobre as sentenças

**2) A partir do tema escolhido, encontre os processos referentes a ele [no banco de sentenças, que chamamos de CJPG (Consulta de Julgados de Primeiro Grau)](https://esaj.tjsp.jus.br/cjpg/), utilizando a Pesquisa Livre, Classe e Assunto (não é preciso utilizar todos os campos, apenas aqueles que o grupo julgar necessário). Anotem os termos pesquisados, as classes e os assuntos e respondam:**

**a) Todos os processos encontrados estão dentro do escopo da pesquisa?**

**b) Existem procesoss que estão dentro do escopo, mas que não foram capturados pela sua pesquisa? Por quê? É possível melhorar?**

**c) É possível fazer a pesquisa realizada acima sem utilizar a Pesquisa Livre, filtrando os processos apenas a partir de Classes e Assuntos? Por quê? (Essa resposta vai variar entre cada grupo).**

### Informações sobre os processos

**3) Agora vamos nos perguntar sobre as informações que temos sobre cada processo.**

**a) A partir da pesquisa realizada no CJPG na questão 2, responda: quais são as informações que você teria de cada processo? Isto é, para cada um dos resultados que a busca gerou, sem acessar as decisões, quais informações estariam disponíveis?**

**b) Copie o número do processo de um caso que você encontrou na CJPG e coloque o número deste processo [na CPOPG (Consulta de Processos de Primeiro Grau)](https://esaj.tjsp.jus.br/cpopg/open.do). Quais informações por processo estão disponíveis neste sistema sem acessar os autos (descreva brevemente)? Compare essas informações com aquelas encontradas na CJPG. Existem informações que existiam na CJPG e que não existem na CPOPG? E o contrário? O que é igual e o que é diferente entre cada sistema, quando às informações disponíveis?**

**c) É possível responder às perguntas de pesquisa do exercício 1 com as informações disponíveis nas consultas públicas da CJPG e CPOPG? Indique quais perguntas podem ser respondidas apenas com as informações e, se houver, quais não podem ser respondidas dessa forma.**

**d) Se houver pelo menos uma pergunta que não pôde ser respondida com as informações disponíveis nos sistemas (CPOPG e CJPG), onde você poderia encontrar essa informação? Para tanto, indique (i) onde a informação pode ser acessada, (ii) se existe algum entrave para o acesso a essa informação e (iii) se é consistente a forma de se encontrar essa informação ao longo dos processos, isto é, se todos os processos contém essa informação no mesmo lugar e com a mesma acessibilidade.**

